projects:
  - title: Gitadora Skill Viewer
    url: "http://gsv.fun"
    github: "https://github.com/ssdh233/gitadora-skill-viewer"
    description: ギタドラのスキルデータを保存するウェブサイト。
  - title: ポックラスクリプト
    url: "https://twitter.com/ssdh233/status/1327288525473996802"
    github: "https://github.com/ssdh233/popn-class"
    description: ポップンクラスの一覧を出すブックマークレットスクリプト。
  - title: PMS Database Support
    url: "http://ssdh233.me/pms-diff-support/"
    github: "https://github.com/ssdh233/pms-diff-support"
    description: PMS Databaseの発狂難易度表にクリアレートを追加したもの（ソート可能）。
  - title: Mahjong-Tiles-Converter
    url: "http://ssdh233.me/mtc/"
    github: "https://github.com/ssdh233/mtc"
    description: 麻雀牌を表示するhtmlを自動的に生成する便利なツールです。
